#Lecture.O.Introduction

# Affine Function 

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]])   # input setting
dense = Dense(units =1, activation='linear')

y_tf = dense(x)    # forward propagation + params intitialization
w, b = dense.get_weights()

y_man = tf.linalg.matmul(x, w) + b

# print results
print('========Input/Weight/Bias=========')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("w: {}\n{}\n".format(w.shape, w))
print("b: {}\n{}\n".format(b.shape, b))
print('========output/Weight/Bias=========')
print("y(Tensorflow):{}\n{}\n)".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))

========Input/Weight/Bias=========
x: (1, 1)
[[10.]]

w: (1, 1)
[[-0.6118276]]

b: (1,)
[0.]

========output/Weight/Bias=========
y(Tensorflow):(1, 1)
[[-6.118276]]
)
y(Manual): (1, 1)
[[-6.118276]]



In [19]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) #input setting(Note : input ->matrix)
dense = Dense(units = 1, activation = 'linear') #imp.an affine function

y_tf = dense(x) #forward propagation + parass initialization
W, B = dense.get_weights()
y_man = tf.linalg.matmul(x,W)+B

print('========Input/Weight/Bias=========')
print("x : {}\n{}\n".format(x.shape,x.numpy()))
print("W : {}\n{}\n".format(x.shape,W))
print("B : {}\n{}\n".format(x.shape,B))
print('========output/Weight/Bias=========')
print("y(Tensorflow):{}\n{}\n)".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))

========Input/Weight/Bias=========
x : (1, 1)
[[10.]]

W : (1, 1)
[[1.0936776]]

B : (1, 1)
[0.]

========output/Weight/Bias=========
y(Tensorflow):(1, 1)
[[10.936776]]
)
y(Manual): (1, 1)
[[10.936776]]



#Params Initalization

In [39]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

#x = tf.constant([[10.]]) #input setting(Note : input ->matrix)
x = tf.random.uniform(shape=(1,10),minval = 0, maxval = 10)
print(x, "\n")

w,b = tf.constant(10.), tf.constant(20.)

w_init,b_init = Constant(w), Constant(b)
print("w_init : {}\nb_init : {}\n".format(w_init, b_init))

dense = Dense(units = 1,
              activation = 'linear',
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)

print(y_tf)

W,B = dense.get_weights()

print("W :{}\n{}\n".format(W.shape,W))

print("B :{}\n{}\n".format(B.shape,B))

tf.Tensor(
[[6.6801605  3.0281186  4.1777554  6.608467   7.4045563  3.0640388
  4.8149347  4.301584   6.8599987  0.48817754]], shape=(1, 10), dtype=float32) 

w_init : <keras.initializers.initializers_v2.Constant object at 0x7f6bf0967350>
b_init : <keras.initializers.initializers_v2.Constant object at 0x7f6bf1cf1410>

tf.Tensor([[494.27792]], shape=(1, 1), dtype=float32)
W :(10, 1)
[[10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]]

B :(1,)
[20.]



# AFfine Function with n Features

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
x = tf.random.uniform(shape=(1,10),minval = 0, maxval = 10)

dense =Dense(units =1)

y_tf = dense(x)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W)+B

print('========Input/Weight/Bias=========')
print("x : {}\n{}\n".format(x.shape,x.numpy()))
print("W : {}\n{}\n".format(x.shape,W))
print("B : {}\n{}\n".format(x.shape,B))
print('========output/Weight/Bias=========')
print("y(Tensorflow):{}\n{}\n)".format(y_tf.shape,y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape,y_man.numpy()))

========Input/Weight/Bias=========
x : (1, 10)
[[7.9917154 1.5939546 3.6623788 5.930132  4.1579294 1.9468498 9.329365
  3.3001912 5.9754906 3.4010065]]

W : (1, 10)
[[-0.7187897 ]
 [ 0.16026056]
 [-0.7038838 ]
 [ 0.05983025]
 [ 0.5176279 ]
 [-0.57064265]
 [ 0.3633433 ]
 [ 0.5104824 ]
 [-0.20740503]
 [-0.64648724]]

B : (1, 10)
[0.]

========output/Weight/Bias=========
y(Tensorflow):(1, 1)
[[-5.034301]]
)
y(Manual): (1, 1)
[[-5.034301]]

