#Activation Layer

In [9]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape = (1,5))

# imp.activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation (Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagatioin (Manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x))/(exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLU(Manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[-0.57420444  1.3829572   0.8061665   0.24386823  0.5594236 ]]
Sigmoid(Tensorflow): (1, 5)
[[0.36026725 0.79946554 0.691292   0.5606667  0.63631916]]
Sigmoid(Manual): (1, 5)
[[0.36026725 0.79946554 0.691292   0.56066674 0.63631916]]
Tanh(Tensorflow): (1, 5)
[[-0.51844037  0.8816117   0.6674701   0.23914608  0.5075497 ]]
Tanh(Manual): (1, 5)
[[-0.5184403   0.88161176  0.66747004  0.23914616  0.5075497 ]]
ReLU(Tensorflow): (1, 5)
[[0.         1.3829572  0.8061665  0.24386823 0.5594236 ]]
ReLU(Manual): (1, 5)
[[0.         1.3829572  0.8061665  0.24386823 0.5594236 ]]


#Activation in Dense Layer

In [12]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape = (1,5))

# imp. artificial neurons
dense_sigmoid = Dense(units = 1, activation='sigmoid')
dense_tanh = Dense(units = 1, activation='tanh')
dense_relu = Dense(units = 1, activation='relu')

# forward propagation (Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("An with Sigmoid= {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("An with  Tanh :{}\n{}".format(y_tanh.shape,y_tanh.numpy()))
print("An with  RelU:{}\n{}".format(y_relu.shape,y_relu.numpy()))

# forward propation (Manual)
print('\n=======\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))

print("Activation value(Tensorflow)= {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("Activation value(manual)= {}\n{}".format(a.shape, a.numpy()))

An with Sigmoid= (1, 1)
[[0.68396497]]
An with  Tanh :(1, 1)
[[-0.77304536]]
An with  RelU:(1, 1)
[[0.]]


Activation value(Tensorflow)= (1, 1)
[[0.68396497]]
Activation value(manual)= (1, 1)
[[0.68396497]]


#Artificial Nuerons

In [14]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape = (1,10))

dense = Dense(units = 1, activation=activation)

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1 / (1 + exp(-x))
elif activation == 'tanh':
  y_man = (exp(x) - exp(-x))/(exp(x) + exp(-x))
elif activation == 'relu':
  y_man = maximum(x, 0)

print("Activation : ",activation)
print("Y_tf : {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("Y_man : {}\n{}\n".format(y_man.shape, y_tf.numpy())) 

Activation :  sigmoid
Y_tf : (1, 1)
[[0.66111875]]

Y_man : (1, 10)
[[0.66111875]]



# Minibatches

##Shapes of Dense Layers

In [20]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 30, 10
x = tf.random.normal(shape=(N, n_feature))

dense = Dense(units=1, activation = 'relu')
y = dense(x)

W, B = dense.get_weights()

# print results
print("Shape of x: ", x.shape)
print("Shape of W: ", W.shape)
print("Shape of B: ", B.shape)

Shape of x:  (30, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


## Output Calculations

In [22]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape = (N ,n_feature))

dense = Dense(units =1, activation = 'sigmoid' )
y_tf  = dense(x)  # forward propagation(Tensorflow)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) + B
y_man = 1/ (1 + tf.math.exp(-y_man)) # forward propagation(Manual)

print("Output(Tensorflow) : \n",y_tf.numpy())
print("Output(Manual) : \n",y_man.numpy())

Output(Tensorflow) : 
 [[0.77179754]
 [0.2844143 ]
 [0.32328323]
 [0.7008535 ]
 [0.32810515]
 [0.62779576]
 [0.64052534]
 [0.28323287]]
Output(Manual) : 
 [[0.7717975 ]
 [0.28441426]
 [0.3232832 ]
 [0.7008535 ]
 [0.32810512]
 [0.62779576]
 [0.64052534]
 [0.28323287]]
