#Activation Layer

In [1]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape = (1,5))

# imp.activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation (Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagatioin (Manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x))/(exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLU(Manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[-1.2483548   0.47802258  0.28850672  0.38235256 -0.53346777]]
Sigmoid(Tensorflow): (1, 5)
[[0.22298506 0.61728084 0.5716305  0.5944404  0.36970848]]
Sigmoid(Manual): (1, 5)
[[0.22298506 0.61728084 0.57163054 0.59444034 0.36970845]]
Tanh(Tensorflow): (1, 5)
[[-0.8478217   0.44465852  0.2807598   0.36474878 -0.48802745]]
Tanh(Manual): (1, 5)
[[-0.84782165  0.44465858  0.2807598   0.36474878 -0.48802736]]
ReLU(Tensorflow): (1, 5)
[[0.         0.47802258 0.28850672 0.38235256 0.        ]]
ReLU(Manual): (1, 5)
[[0.         0.47802258 0.28850672 0.38235256 0.        ]]


#Activation in Dense Layer

In [3]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape = (1,5))

# imp. artificial neurons
dense_sigmoid = Dense(units = 1, activation='sigmoid')
dense_tanh = Dense(units = 1, activation='tanh')
dense_relu = Dense(units = 1, activation='relu')

# forward propagation (Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("An with Sigmoid= {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("An with  Tanh :{}\n{}".format(y_tanh.shape,y_tanh.numpy()))
print("An with  RelU:{}\n{}".format(y_relu.shape,y_relu.numpy()))

# forward propation (Manual)
print('\n=======\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))

print("Activation value(Tensorflow)= {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("Activation value(manual)= {}\n{}".format(a.shape, a.numpy()))

An with Sigmoid= (1, 1)
[[0.81231654]]
An with  Tanh :(1, 1)
[[-0.8373822]]
An with  RelU:(1, 1)
[[0.]]


Activation value(Tensorflow)= (1, 1)
[[0.81231654]]
Activation value(manual)= (1, 1)
[[0.8123165]]


#Artificial Nuerons

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape = (1,10))

dense = Dense(units = 1, activation=activation)

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1 / (1 + exp(-x))
elif activation == 'tanh':
  y_man = (exp(x) - exp(-x))/(exp(x) + exp(-x))
elif activation == 'relu':
  y_man = maximum(x, 0)

print("Activation : ",activation)
print("Y_tf : {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("Y_man : {}\n{}\n".format(y_man.shape, y_tf.numpy())) 

Activation :  sigmoid
Y_tf : (1, 1)
[[0.66111875]]

Y_man : (1, 10)
[[0.66111875]]



# Minibatches

##Shapes of Dense Layers

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 30, 10
x = tf.random.normal(shape=(N, n_feature))

dense = Dense(units=1, activation = 'relu')
y = dense(x)

W, B = dense.get_weights()

# print results
print("Shape of x: ", x.shape)
print("Shape of W: ", W.shape)
print("Shape of B: ", B.shape)

Shape of x:  (30, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


In [23]:
N, n_feature = 10, 3

x = tf.random.normal(shape = (N, n_feature))
print("x : {}".format(x.numpy()))

dense = Dense(units=2, activation = 'tanh')

y_tf = dense(x)
W, B = dense.get_weights()

print("W : {}, B : {}".format(W, B))
print(y_tf)

x : [[ 0.40060934 -0.44682223 -1.8047901 ]
 [ 0.46549374  0.9076447   1.4527411 ]
 [-0.1650866  -0.45307422 -0.3584306 ]
 [-1.4014648   1.6066442  -2.6268694 ]
 [ 0.40783498 -0.40597698  1.0593624 ]
 [-2.098349   -0.6596695  -0.02338341]
 [-1.0895957   0.75978273  0.48283786]
 [-1.2704546  -0.70491207  1.1227605 ]
 [ 0.5607225   0.2020597   1.560491  ]
 [ 0.4655271   1.7590245   0.10509004]]
W : [[ 0.0092988   0.4181453 ]
 [-0.4762122   0.47262526]
 [ 0.66994023  0.7448027 ]], B : [0. 0.]
tf.Tensor(
[[-0.75846636 -0.8827033 ]
 [ 0.49702463  0.93610847]
 [-0.02589691 -0.5006136 ]
 [-0.9875874  -0.94503564]
 [ 0.7196088   0.64557564]
 [ 0.2719469  -0.8356589 ]
 [-0.04843928  0.25719473]
 [ 0.79173213 -0.02815129]
 [ 0.74178046  0.90373236]
 [-0.64280313  0.8020343 ]], shape=(10, 2), dtype=float32)


## Output Calculations

In [24]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape = (N ,n_feature))

dense = Dense(units =1, activation = 'sigmoid' )
y_tf  = dense(x)  # forward propagation(Tensorflow)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) + B
y_man = 1/ (1 + tf.math.exp(-y_man)) # forward propagation(Manual)

print("Output(Tensorflow) : \n",y_tf.numpy())
print("Output(Manual) : \n",y_man.numpy())

Output(Tensorflow) : 
 [[0.96384585]
 [0.02493128]
 [0.7246929 ]
 [0.6946141 ]
 [0.70135736]
 [0.91548294]
 [0.35290822]
 [0.4807868 ]]
Output(Manual) : 
 [[0.9638458 ]
 [0.02493129]
 [0.7246928 ]
 [0.6946141 ]
 [0.70135736]
 [0.9154829 ]
 [0.3529082 ]
 [0.48078677]]
