#Shapes of cacaded Dense Layers

In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N,n_feature = 4,10
X = tf.random.normal(shape = (N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units = n_neurons[0],activation = 'sigmoid')
dense2 = Dense(units = n_neurons[1],activation = 'sigmoid')

# forward proparation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)
print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)



#Dense Layers with Python List

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N,n_feature = 4,10
X = tf.random.normal(shape = (N, n_feature))

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units = n_neuron, activation = 'relu')
  dense_layers.append(dense)

#print(dense_layers)

print("Input: ", X.shape)
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print("After dense layer", dense_idx + 1)
  print(X.shape, '\n')

Y = X
#print(Y)

Input:  (4, 10)
After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 

After dense layer 5
(4, 50) 

After dense layer 6
(4, 60) 

After dense layer 7
(4, 70) 

After dense layer 8
(4, 80) 

After dense layer 9
(4, 90) 

After dense layer 10
(4, 100) 



#Output Calculations

In [7]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N,n_feature = 4,10
X = tf.random.normal(shape = (N, n_feature))
X_cp = tf.identity(X)    # Function of copy value = identify

n_neurons = [3, 4, 5]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units = n_neuron, activation = 'sigmoid')
  dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)

print("Y(Tensorflow): \n", X.numpy())

# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1 + exp(-X_cp))

print("Y(Manual): \n", X_cp.numpy())

Y(Tensorflow): 
 [[0.5562441  0.6211207  0.54774314 0.56713814 0.5340434 ]
 [0.5895257  0.65184546 0.5494538  0.60655797 0.5116706 ]
 [0.5699274  0.64533144 0.55729026 0.5853602  0.52636504]
 [0.5744212  0.65853083 0.56422377 0.5912091  0.53071284]]
Y(Manual): 
 [[0.5562441  0.6211207  0.54774314 0.56713814 0.5340434 ]
 [0.5895257  0.65184546 0.5494538  0.60655797 0.5116706 ]
 [0.56992733 0.64533144 0.55729026 0.5853602  0.52636504]
 [0.5744212  0.6585309  0.56422377 0.5912091  0.5307128 ]]
