#Model Implementation with Sequential Method

In [1]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

n_neurons = [3,4,5,6]

model = list()
for n_neuron in n_neurons:
  model.append(Dense(units = n_neuron, activation ='sigmoid'))

print(model)

model = Sequential()
for n_neuron in n_neurons:
  model.add(Dense(units = n_neuron, activation ='sigmoid'))

print(model)

model = Sequential()
model.add(Dense(units = 10, activation = 'sigmoid'))
model.add(Dense(units = 20, activation = 'sigmoid'))

model

[<keras.layers.core.dense.Dense object at 0x7f42cb725990>, <keras.layers.core.dense.Dense object at 0x7f42cb6b5650>, <keras.layers.core.dense.Dense object at 0x7f42cb6b5bd0>, <keras.layers.core.dense.Dense object at 0x7f42cb6aa090>]


#Model Implementation with Model-subclassing

In [8]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Model

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units = 10, activation = 'sigmoid')
    self.dense2 = Dense(units = 20, activation = 'sigmoid')

model = TestModel()
print(model.dense1)
print(model.dense2)

#Forward Propagation of Models

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape = (4,20))

# Sequential method
model = Sequential()
model.add(Dense(units = 10, activation = 'sigmoid'))
model.add(Dense(units = 20, activation = 'sigmoid'))

Y = model(X)
print(Y.numpy())

# Model-subclassing
class TestModel(Model):
  def __init__(self):
    super().__init__()

    self.dense1 = Dense(units = 10, activation = 'sigmoid')
    self.dense2 = Dense(units = 20, activation = 'sigmoid')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    return x

model2 = TestModel()
Y = model(X)
print(Y.numpy())

[[0.595822   0.5062761  0.44862932 0.6080843  0.5929024  0.56905776
  0.59795725 0.6457006  0.42639393 0.4419541  0.62644905 0.45197493
  0.49371198 0.42744088 0.5154752  0.40789318 0.45802766 0.25517756
  0.50890905 0.52559245]
 [0.62370217 0.49338374 0.49531743 0.6551172  0.54148537 0.50660974
  0.5544833  0.6574503  0.4916351  0.4169731  0.59890544 0.39285675
  0.58710456 0.4515927  0.48540843 0.43084994 0.512431   0.27141
  0.52744025 0.49313927]
 [0.62823236 0.4463143  0.43349788 0.64515406 0.51951355 0.48693603
  0.55318606 0.5843244  0.5539373  0.51542056 0.52310705 0.40997395
  0.4707339  0.50769657 0.5217279  0.46551526 0.55856997 0.36341336
  0.46904653 0.531624  ]
 [0.6197539  0.57022285 0.37547112 0.61519486 0.62123317 0.56189793
  0.50353634 0.6373088  0.5410442  0.4829559  0.5802108  0.43902904
  0.456706   0.4270836  0.5184122  0.43535572 0.66027266 0.22660565
  0.57454056 0.5168354 ]]
[[0.595822   0.5062761  0.44862932 0.6080843  0.5929024  0.56905776
  0.59795725 0.645

In [28]:
class TestModel(Model):
  def __init__(self, n_neurons):
    super().__init__()

    self.n_neurons = n_neurons

    self.dense_layers = list()
    for n_neuron in n_neurons:
      self.dense_layers.append(Dense(units = n_neuron, activation = 'sigmoid'))
  
  def call(self, x):
    for dense in self.dense_layers:
      x = dense(x)
    return x

n_neurons = [3,4,5]
model = TestModel(n_neurons)
Y = model(X)
print(Y.numpy())

[[0.58466893 0.4382677  0.5700309  0.4688894  0.6036413 ]
 [0.58372325 0.4402186  0.5786819  0.46857554 0.60798824]
 [0.5595476  0.46595645 0.57743067 0.4818186  0.5899653 ]
 [0.5671886  0.46026754 0.5795088  0.47916496 0.5964515 ]]


In [27]:
class TestModel(Model):
  def __init__(self, n_neurons):
    super().__init__()

    self.n_neurons = n_neurons

    self.models = Sequential()
    for n_neuron in n_neurons:
      self.models.add(Dense(units = n_neuron, activation = 'sigmoid'))
  
  def call(self, x):
    x = self.models(x)
    return x

n_neurons = [3,4,5]
model = TestModel(n_neurons)
Y = model(X)
print(Y.numpy())

[[0.4069396  0.59791857 0.49244004 0.34222192 0.34134033]
 [0.3906469  0.59189993 0.49378747 0.34664372 0.340837  ]
 [0.4102192  0.60826993 0.50385845 0.33146542 0.34200102]
 [0.41747558 0.6162493  0.5110502  0.32693714 0.36171797]]


#Layers in Models

In [37]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10,activation='sigmoid'))
model.add(Dense(units=20,activation='sigmoid'))

Y = model(X)

print(type(model.layers))
print(model.layers)

dense1 = model.layers[0]
print(dir(dense1))
#for tmp in dir(dense1):
#  print(tmp)

for layer in model.layers:
  w, b = layer.get_weights()
  print(w.shape, b.shape)

<class 'list'>
[<keras.layers.core.dense.Dense object at 0x7f42c64c3a10>, <keras.layers.core.dense.Dense object at 0x7f42c648dfd0>]
['_TF_MODULE_IGNORED_PROPERTIES', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_activity_regularizer', '_add_trackable', '_add_trackable_child', '_add_variable_with_custom_getter', '_auto_track_sub_layers', '_autocast', '_autographed_call', '_build_input_shape', '_call_accepts_kwargs', '_call_arg_was_passed', '_call_fn_arg_defaults', '_call_fn_arg_positions', '_call_fn_args', '_call_full_argspec', '_callable_losses', '_cast_single_input', '_checkpoint_dependencies', '_clear_losses', '_compute_dtype', '_compute_dtype_ob

#Trainable Variables in Models

In [41]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

X = tf. random.normal (shape = (4, 10))

model = Sequential()
model.add(Dense(units=10, activation = 'sigmoid'))
model.add(Dense(units=20, activation = 'sigmoid'))

Y= model(X)

print (type(model.trainable_variables) )
print (len(model.trainable_variables) )

for train_var in model.trainable_variables:
  print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
