## shapes of Dense Layers

In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8,10
X = tf.random.normal(shape = (N, n_feature))

n_neuron =3
dense = Dense(units = n_neuron, activation = 'sigmoid')
y = dense(X)

W, B = dense.get_weights()

print('=============Input/Weight/Bias============')
print("X : ",X.shape)
print("W : ",W.shape)
print("B : ",B.shape)
print("Y : ",y.shape)
W


=============Input/Weight/Bias============
X :  (8, 10)
W :  (10, 3)
B :  (3,)
Y :  (8, 3)


array([[ 0.6059575 , -0.53989553,  0.5842935 ],
       [ 0.24810088, -0.26982102, -0.01265758],
       [ 0.5433054 ,  0.64605165, -0.43077606],
       [ 0.6608654 , -0.12573808,  0.5571003 ],
       [-0.5218115 ,  0.21575993,  0.46507215],
       [ 0.44914937, -0.2926656 , -0.5298247 ],
       [ 0.41172147,  0.21016634,  0.32056993],
       [ 0.3300531 ,  0.08394587, -0.641998  ],
       [ 0.01340139, -0.01002228, -0.39048174],
       [-0.59244263, -0.611539  ,  0.3218944 ]], dtype=float32)

## Output Calculations

In [4]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul
import numpy as np


N, n_feature = 4,10
X = tf.random.normal(shape = (N, n_feature))
#print(X.numpy())

n_neuron =3
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n",Y_tf.numpy())

# calculation with matrix multiplication
z = matmul(X,W) + B
Y_man_matmul = 1/(1 + exp(-z))
print("Y(with matrix multiplication): \n",Y_man_matmul.numpy())

# calculation with dot products
Y_man_vec = np.zeros(shape = (N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]
  #print(x.numpy())

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1/(1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(Tensorflow): 
 [[0.87899536 0.87670314 0.86235094]
 [0.6448279  0.5697081  0.75799716]
 [0.700753   0.67615694 0.16484109]
 [0.17118874 0.31851733 0.5146449 ]]
Y(with matrix multiplication): 
 [[0.87899536 0.87670314 0.862351  ]
 [0.6448279  0.5697081  0.7579972 ]
 [0.70075303 0.676157   0.16484109]
 [0.17118877 0.31851727 0.5146449 ]]
Y(with dot products): 
 [[0.87899533 0.87670321 0.86235094]
 [0.6448279  0.56970812 0.75799722]
 [0.70075299 0.67615696 0.16484106]
 [0.17118879 0.31851728 0.51464489]]
