## shapes of Dense Layers

In [5]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8,10
X = tf.random.normal(shape = (N, n_feature))

n_neuron =3
dense = Dense(units = n_neuron, activation = 'sigmoid')
y = dense(X)

W, B = dense.get_weights()

print('=============Input/Weight/Bias============')
print("X : ",X.shape)
print("W : ",W.shape)
print("B : ",B.shape)
print("Y : ",y.shape)
W


=============Input/Weight/Bias============
X :  (8, 10)
W :  (10, 3)
B :  (3,)
Y :  (8, 3)


array([[ 0.03725213, -0.28527635,  0.31747103],
       [-0.67127013, -0.15427965, -0.18164021],
       [ 0.19786781, -0.2780355 , -0.04140073],
       [-0.4463778 ,  0.13889605,  0.4643606 ],
       [ 0.5063791 , -0.48093197, -0.06707811],
       [ 0.56053936,  0.3616835 ,  0.36278975],
       [ 0.39924407,  0.4616989 , -0.55644774],
       [ 0.01700044,  0.49351883,  0.19757563],
       [-0.51457274, -0.09676057,  0.5971383 ],
       [-0.56625867,  0.01165867,  0.55254245]], dtype=float32)

## Output Calculations

In [12]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense
from tensorflow.linalg import matmul


N, n_feature = 4,10
X = tf.random.normal(shape = (N, n_feature))
#print(X.numpy())

n_neuron =3
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n",Y_tf.numpy())

# calculation with matrix multiplication
z = matmul(X,W) + B
Y_man_matmul = 1/(1 + exp(-z))
print("Y(with matrix multiplication): \n",Y_man_matmul.numpy())

# calculation with dot products
Y_man_vec = np.zeros(shape = (N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]
  #print(x.numpy())

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1/(1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(Tensorflow): 
 [[0.04839677 0.39831448 0.82563484]
 [0.81614065 0.5496268  0.73260194]
 [0.6920482  0.75446045 0.3984964 ]
 [0.3616768  0.67493844 0.8902843 ]]
Y(with matrix multiplication): 
 [[0.04839677 0.39831448 0.8256348 ]
 [0.81614065 0.5496268  0.73260194]
 [0.6920482  0.7544605  0.39849636]
 [0.36167678 0.6749384  0.89028424]]
Y(with dot products): 
 [[0.04839675 0.39831448 0.8256348 ]
 [0.81614068 0.54962683 0.73260196]
 [0.69204816 0.75446048 0.39849639]
 [0.36167682 0.67493842 0.89028428]]
