#Model Implementation with Sequential Method

In [ ]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

n_neurons = [3,4,5,6]

model = list()
for n_neuron in n_neurons:
  model.append(Dense(units = n_neuron, activation ='sigmoid'))

print(model)

model = Sequential()
for n_neuron in n_neurons:
  model.add(Dense(units = n_neuron, activation ='sigmoid'))

print(model)

model = Sequential()
model.add(Dense(units = 10, activation = 'sigmoid'))
model.add(Dense(units = 20, activation = 'sigmoid'))

model

[<keras.layers.core.dense.Dense object at 0x7f42cb725990>, <keras.layers.core.dense.Dense object at 0x7f42cb6b5650>, <keras.layers.core.dense.Dense object at 0x7f42cb6b5bd0>, <keras.layers.core.dense.Dense object at 0x7f42cb6aa090>]


#Model Implementation with Model-subclassing

In [ ]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Model

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units = 10, activation = 'sigmoid')
    self.dense2 = Dense(units = 20, activation = 'sigmoid')

model = TestModel()
print(model.dense1)
print(model.dense2)

#Forward Propagation of Models

In [18]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape = (4, 20))
print(X)

model = Sequential()
model.add(Dense(units = 10, activation = 'sigmoid'))
model.add(Dense(units = 20, activation = 'sigmoid'))

Y = model(X)
print(Y.numpy())

class TestModel (Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units = 10, activation = 'sigmoid')
    self.dense2 = Dense(units = 20, activation = 'sigmoid')
  
  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    return x

model = TestModel()
Y = model(X)
print(Y.numpy())

tf.Tensor(
[[-0.2995721  -0.841462   -0.56068563  0.21620177 -0.07809762  0.23377818
  -2.453409   -1.148872   -0.6921745   1.9547098   0.28118825 -0.4185641
   0.4064971  -1.304589   -0.44809777 -1.1792533  -1.2441872  -1.2954416
   1.2645842   0.9810807 ]
 [-2.2410634   0.03191766  0.21528724 -2.0882602  -1.8877587  -0.7567812
   0.35483718 -1.2679403   0.09677007 -0.79198796 -0.14693882  0.1915156
   1.113539    0.5383226   0.13759533  1.1307248  -0.8102459   1.3367933
  -0.311903    0.40029585]
 [-0.90530276 -3.0207632   0.13272966 -1.6777105   1.4519361   0.85505277
  -0.39802876  2.04169    -0.45167962 -1.3792131   0.6025435  -1.067507
  -0.42448768 -0.51317537  0.24554124 -1.6009679  -0.2598673   0.2907673
  -0.24928302  0.31843418]
 [ 1.7638983   0.60709566 -0.02359713  0.60597384 -0.1940744  -1.0780888
  -0.00782978  0.32354155 -0.9017634  -1.2146714  -1.2826699   0.87772185
   0.94380313 -1.3873864   1.507118   -0.9038643   0.03092242 -1.0948111
  -0.88325274  0.22222847]], s

In [ ]:
class TestModel(Model):
  def __init__(self, n_neurons):
    super().__init__()

    self.n_neurons = n_neurons

    self.dense_layers = list()
    for n_neuron in n_neurons:
      self.dense_layers.append(Dense(units = n_neuron, activation = 'sigmoid'))
  
  def call(self, x):
    for dense in self.dense_layers:
      x = dense(x)
    return x

n_neurons = [3,4,5]
model = TestModel(n_neurons)
Y = model(X)
print(Y.numpy())

[[0.58466893 0.4382677  0.5700309  0.4688894  0.6036413 ]
 [0.58372325 0.4402186  0.5786819  0.46857554 0.60798824]
 [0.5595476  0.46595645 0.57743067 0.4818186  0.5899653 ]
 [0.5671886  0.46026754 0.5795088  0.47916496 0.5964515 ]]


In [ ]:
class TestModel(Model):
  def __init__(self, n_neurons):
    super().__init__()

    self.n_neurons = n_neurons

    self.models = Sequential()
    for n_neuron in n_neurons:
      self.models.add(Dense(units = n_neuron, activation = 'sigmoid'))
  
  def call(self, x):
    x = self.models(x)
    return x

n_neurons = [3,4,5]
model = TestModel(n_neurons)
Y = model(X)
print(Y.numpy())

[[0.4069396  0.59791857 0.49244004 0.34222192 0.34134033]
 [0.3906469  0.59189993 0.49378747 0.34664372 0.340837  ]
 [0.4102192  0.60826993 0.50385845 0.33146542 0.34200102]
 [0.41747558 0.6162493  0.5110502  0.32693714 0.36171797]]


#Layers in Models

In [24]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10,activation='sigmoid'))
model.add(Dense(units=20,activation='sigmoid'))

Y = model(X)
print(model.layers)
print(type(model.layers))

dense1 = model.layers[0]
for tmp in dir(dense1):
  print(tmp)

[<keras.layers.core.dense.Dense object at 0x7f66bbe8d390>, <keras.layers.core.dense.Dense object at 0x7f66bbde5d50>]
<class 'list'>
_TF_MODULE_IGNORED_PROPERTIES
__call__
__class__
__delattr__
__dict__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getstate__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__setstate__
__sizeof__
__str__
__subclasshook__
__weakref__
_activity_regularizer
_add_trackable
_add_trackable_child
_add_variable_with_custom_getter
_auto_track_sub_layers
_autocast
_autographed_call
_build_input_shape
_call_accepts_kwargs
_call_arg_was_passed
_call_fn_arg_defaults
_call_fn_arg_positions
_call_fn_args
_call_full_argspec
_callable_losses
_cast_single_input
_checkpoint_dependencies
_clear_losses
_compute_dtype
_compute_dtype_object
_dedup_weights
_default_training_arg
_deferred_dependencies
_delete_tracking
_deserialization_dependencies
_deserialize_from_proto
_dtype
_dtype

In [26]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10,activation='sigmoid'))
model.add(Dense(units=20,activation='sigmoid'))

Y = model(X)

print(type(model.layers))
print(model.layers)

dense1 = model.layers[0]
print(dir(dense1))
#for tmp in dir(dense1):
#  print(tmp)

for layer in model.layers:
  w, b = layer.get_weights()
  print(w.shape, b.shape)
  #print(w, b)

<class 'list'>
[<keras.layers.core.dense.Dense object at 0x7f66bcf82190>, <keras.layers.core.dense.Dense object at 0x7f66bcf82510>]
['_TF_MODULE_IGNORED_PROPERTIES', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_activity_regularizer', '_add_trackable', '_add_trackable_child', '_add_variable_with_custom_getter', '_auto_track_sub_layers', '_autocast', '_autographed_call', '_build_input_shape', '_call_accepts_kwargs', '_call_arg_was_passed', '_call_fn_arg_defaults', '_call_fn_arg_positions', '_call_fn_args', '_call_full_argspec', '_callable_losses', '_cast_single_input', '_checkpoint_dependencies', '_clear_losses', '_compute_dtype', '_compute_dtype_ob

#Trainable Variables in Models

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

X = tf. random.normal (shape = (4, 10))

model = Sequential()
model.add(Dense(units=10, activation = 'sigmoid'))
model.add(Dense(units=20, activation = 'sigmoid'))

Y= model(X)

print (type(model.trainable_variables) )
print (len(model.trainable_variables) )

for train_var in model.trainable_variables:
  print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
