#IO of Softmax

In [10]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape = (3, 5), minval = -10, maxval = 10)

softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print("Logits: \n", logit.numpy())
print("Probabilities: \n", softmax_value.numpy())
print("Sum of softmax values: \n", softmax_sum)      # sum of probatility is '1'

Logits: 
 [[ 4.3396807 -8.715816   7.466852  -7.893014  -8.785815 ]
 [ 6.121073   9.583216  -9.572024   6.9046764  3.2323723]
 [ 3.4484434 -7.8913093 -9.7154    -4.282942  -6.402025 ]]
Probabilities: 
 [[4.2000249e-02 8.9809511e-08 9.5799935e-01 2.0448435e-07 8.3737859e-08]
 [2.8465515e-02 9.0762955e-01 4.3540558e-09 6.2320914e-02 1.5840627e-03]
 [9.9949491e-01 1.1884715e-05 1.9177685e-06 4.3861417e-04 5.2695850e-05]]
Sum of softmax values: 
 tf.Tensor([0.99999994 1.         1.        ], shape=(3,), dtype=float32)


#Softmax in Dense Layers

In [11]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape = (8,5),minval = -10,maxval = 10)
dense = Dense(units = 8, activation = 'softmax')    # Number of Class can be replaced units

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[1.         1.0000001  0.99999994 0.99999994 1.         1.
 1.         1.        ], shape=(8,), dtype=float32)


#Multi -class classifiers

In [14]:
import tensorflow as tf

from tensorflow.keras.models import Model

from tensorflow.keras.layers import Dense

class TestModel (Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=5, activation='relu')
    self.dense2 = Dense(units=5, activation='relu')
    self.dense3 = Dense(units=3, activation='softmax')
    
  def call(self, x):
    print("X: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense1(x)
    print("A1: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense2(x)
    print("A2: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense3(x)
    print("Y: {}\n{}\n".format(x.shape, x.numpy()))
    print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
    return x

model = TestModel()

X = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
Y = model(X)

X: (8, 5)
[[ 4.8054123   4.2950897  -4.8526073  -9.107814    4.7218943 ]
 [-0.35173416 -6.9219017  -7.2840285  -1.7038517  -0.51423264]
 [-3.111596    6.291933    9.2593975  -7.3100114  -2.5422335 ]
 [ 6.0760727   7.867668    5.128045   -2.2708392  -5.3513455 ]
 [-9.538958    4.0546627   4.8116446   4.433382    0.8836918 ]
 [-3.7193823  -8.717945   -1.7432022  -4.134214    6.779587  ]
 [ 1.9901228   9.675007    2.2939224   5.871682   -3.2672524 ]
 [ 6.9586544   3.3601856   2.7380161  -2.9245472  -1.1252518 ]]

A1: (8, 5)
[[0.         1.9800395  4.388852   0.         5.5344267 ]
 [0.         0.         0.         6.3431244  8.113352  ]
 [0.         2.3168523  7.934172   0.         0.44426653]
 [8.765981   2.3347871  5.9780383  0.         0.        ]
 [0.         0.         0.22049698 4.6971807  0.        ]
 [0.         3.0472007  0.         2.8990216  7.829063  ]
 [8.618544   0.         1.7472771  0.         0.        ]
 [5.539313   4.899703   5.4289746  0.         0.        ]]

A2: (8,