# Dataset for Regression

In [11]:
import tensorflow as tf

N,n_feature  = 8,5
t_weights = tf.constant([1,2,3,4,5],dtype = tf.float32)
t_bias = tf.constant([10],dtype = tf.float32)

x = tf.random.normal(mean = 0, stddev = 1, shape = (N, n_feature))

Y = tf.reduce_sum(t_weights * x, axis = 1) + t_bias

print("X(shape/dtype/data) : {} / {}\n{}\n".format(x.shape, x.dtype, x.numpy()))
print("Y(shape/dtype/data) : {} / {}\n{}\n".format(Y.shape, Y.dtype, Y.numpy()))

X(shape/dtype/data) : (8, 5) / <dtype: 'float32'>
[[ 1.5901747   0.19254878 -2.3789892  -0.00310367  0.05238293]
 [ 0.35451818 -1.5379431  -0.77632874  0.38580087 -0.09287577]
 [-0.80447125 -0.07716593  0.27896783  0.74895996 -1.0611944 ]
 [ 0.28185877  1.2502004  -0.9671688  -1.2074783   0.3713524 ]
 [-0.42789787 -1.2144711  -0.02483525 -0.02753482  0.29347238]
 [ 0.45456186  1.9249383  -1.793262   -0.3350933   0.04995184]
 [-0.52889794  0.69757015  0.6701312  -1.3189183  -0.442792  ]
 [ 0.913333   -0.69714904 -1.8073232   0.51132375  0.44447935]]

Y(shape/dtype/data) : (8,) / <dtype: 'float32'>
[5.087805  6.0284705 7.5679684 6.907602  8.425877  7.8340387 5.387003
 8.364758 ]



# Dataset for BInary Classification

In [12]:
import tensorflow as tf

N,n_feature  = 8,5
t_weights = tf.constant([1,2,3,4,5],dtype = tf.float32)
t_bias = tf.constant([10],dtype = tf.float32)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y = tf.reduce_sum(t_weights*X,axis=1) + t_bias
print (Y)
Y = Y > 5
print(Y)
Y = tf.cast(Y, tf.int32)  
print(Y)

#print("X(shape/dtype/data) : {} / {}\n{}\n".format(X.shape,X.dtype.X.numpy()))
#print("Y(shape/dtype/data) : {} / {}\n{}\n".format(X.shape,X.dtype.X.numpy()))

tf.Tensor(
[10.862707   8.931587   3.3619256 13.457423   4.254159   0.8218622
 19.219128  10.558226 ], shape=(8,), dtype=float32)
tf.Tensor([ True  True False  True False False  True  True], shape=(8,), dtype=bool)
tf.Tensor([1 1 0 1 0 0 1 1], shape=(8,), dtype=int32)
